"""add post_id to apratments

Revision ID: 4c5d6c1fae92
Revises: 527a40e7a8ad
Create Date: 2025-04-04 19:33:19.444034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c5d6c1fae92'
down_revision: Union[str, None] = '527a40e7a8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraper_users')
    op.add_column('apartments', sa.Column('post_id', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'post_id')
    op.create_table('scraper_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_login', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='scraper_users_pkey'),
    sa.UniqueConstraint('email', 'source', name='uix_email_source')
    )
    # ### end Alembic commands ###
